import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/core/styles/globals.css";
import Providers from "@/core/providers";
import Sidebar from "@/core/components/sidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="grid grid-cols-[auto,1fr] gap-4 min-h-screen">
          <Sidebar />
          <main className="p-4">
            <Providers>{children}</Providers>
          </main>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
